### ISSUE TITLE
Lo

### ISSUE THREAD

**Issue by qnetvova** [algolia/ui-components#39]
## Reproduction

[**Preview →**](https://codesandbox.io/s/github/algolia/ui-components/tree/next/examples/demo?file=/src/App.js)

**Steps**

1. Click on `...`
2. See error

## Environment

- OS: [e.g., Windows / Linux / macOS / iOS / Android]
- Browser: [e.g., Chrome, Safari]
- Library version: [e.g., 1.0.0]

**Comment by qnetvova** [comment]
.

**Comment by qnetvova** [comment]
Vv

**Comment by francoischalifour** [comment]
Closing this. Feel free to open another issue with information if that's what you meant to do.
